### ISSUE TITLE
virus_to_beds

### ISSUE THREAD

**Issue by drli** [ChangLab/FAST-iCLIP#22]
I was running your example datasets  and got the following error.   Any advices?

Run samtools.
Traceback (most recent call last):
  File "/home/hul/.local/bin/fasticlip", line 9, in <module>
    load_entry_point('fasticlip==0.9.3', 'console_scripts', 'fasticlip')()
  File "build/bdist.linux-x86_64/egg/fasticlip/fasticlip.py", line 255, in main
UnboundLocalError: local variable 'virus_to_beds' referenced before assignment

**Comment by bdo311** [comment]
Whoops I don't know how that bug got in there but I believe it should be fixed. Thanks!
