### ISSUE TITLE
PyQt4

### ISSUE THREAD

**Issue by andypohl** [ChangLab/FAST-iCLIP#23]
I tried carefully to abide by all the dependencies.  I have FASTX-tools 0.0.14 instead of 0.0.13 but otherwise everything you've outlined.  I forked this repo and added a Dockerfile because honestly this has been a very difficult install, even for bioinformatics standards.  Your dependency structure is not in line with the standards put forth by conda or pip, because if I try to use package managers and hit your dependency requirements, I'll have PyQt5 installed and not PyQt4.  So I get an error:

```
$ git clone https://github.com/andypohl/FAST-iCLIP.git
$ cd FAST-iCLIP/
$ docker build -t andypohl/fasticlip .
$ docker run -ti --rm andypohl/fasticlip
(inside container)
andy@f1dc5b116d05:~$  fasticlip
/home/andy/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/home/andy/conda/bin/fasticlip", line 11, in <module>
    load_entry_point('fasticlip==0.9.3', 'console_scripts', 'fasticlip')()
  File "/home/andy/conda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/home/andy/conda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/home/andy/conda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2258, in load
  File "/home/andy/conda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "build/bdist.linux-x86_64/egg/fasticlip/fasticlip.py", line 5, in <module>
  File "build/bdist.linux-x86_64/egg/fasticlip/helper.py", line 10, in <module>
  File "/home/andy/conda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/andy/conda/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/home/andy/conda/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import QtCore
  File "/home/andy/conda/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 31, in <module>
    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
  File "/home/andy/conda/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py", line 137, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named PyQt4
andy@f1dc5b116d05:~$
```

If I try installing PyQt4 after the fact with conda, it'll prompt me to downgrade other things, namely matplotlib 1.5.3 -> 1.5.1.  Anyway, then I get another error:

```
andy@ba7d50d2c02f:~$ conda install pyqt=4.11.4
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /home/andy/conda:

The following NEW packages will be INSTALLED:

    harfbuzz:   0.9.39-2         
    pango:      1.40.3-1         

The following packages will be DOWNGRADED:

    matplotlib: 1.5.3-np111py27_1 --> 1.5.1-np111py27_0
    pyqt:       5.6.0-py27_2      --> 4.11.4-py27_4    
    qt:         5.6.2-4           --> 4.8.7-4          

Proceed ([y]/n)? y

harfbuzz-0.9.3 100% |###################################################################| Time: 0:00:00   5.90 MB/s
pango-1.40.3-1 100% |###################################################################| Time: 0:00:00   9.46 MB/s
qt-4.8.7-4.tar 100% |###################################################################| Time: 0:00:04   6.90 MB/s
pyqt-4.11.4-py 100% |###################################################################| Time: 0:00:00   6.00 MB/s
matplotlib-1.5 100% |###################################################################| Time: 0:00:01   7.28 MB/s
andy@ba7d50d2c02f:~$ fasticlip
/home/andy/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/home/andy/conda/bin/fasticlip", line 11, in <module>
    load_entry_point('fasticlip==0.9.3', 'console_scripts', 'fasticlip')()
  File "/home/andy/conda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/home/andy/conda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/home/andy/conda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2258, in load
  File "/home/andy/conda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "build/bdist.linux-x86_64/egg/fasticlip/fasticlip.py", line 5, in <module>
  File "build/bdist.linux-x86_64/egg/fasticlip/helper.py", line 10, in <module>
  File "/home/andy/conda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/andy/conda/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/home/andy/conda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
  File "/home/andy/conda/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import QtCore
  File "/home/andy/conda/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 31, in <module>
    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
  File "/home/andy/conda/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py", line 124, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: libSM.so.6: cannot open shared object file: No such file or directory
```
I've been trying so hard to install this and it's just problem after problem.  Please, what am I missing here?

**Comment by broughtonjp** [comment]
I think I ran into something similar earlier while trying to install. I believe the error occurred when importing pyplot from matplotlib.

Try using: 
```
import matplotlib as mpl; mpl.use('Agg')
import matplotlib.pyplot as plt
```
Wherever this occurs:
```
import matplotlib as mpl
import matplotlib.pyplot as plt
```

**Comment by andypohl** [comment]
Worked.  The issue was a problem with Conda's packaging of matplotlib, not with matplotlib or FAST-iCLIP.  I'll make a pull request with my changes, which should address this in a Conda-specific way.
