### ISSUE TITLE
Not able to run example

### ISSUE THREAD

**Issue by marencc** [ChangLab/FAST-iCLIP#30]
Hi! I'm trying to run your example, however I find the attached problem. 
Would you please advise me on how to proceed ?

Many thanks!!

```
fasticlip -i rawdata/example_MMhur_R1.fastq rawdata/example_MMhur_R2.fastq --GRCm38 -s docs/GRCm38/GRCm38_STAR/ -n Mmhur -o results
Traceback (most recent call last):
  File "/usr/local/bin/fasticlip", line 11, in <module>
    load_entry_point('fasticlip==0.9.3', 'console_scripts', 'fasticlip')()
  File "/home/mecc/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/mecc/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2649, in load_entry_point
    return ep.load()
  File "/home/mecc/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2303, in load
    return self.resolve()
  File "/home/mecc/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/fasticlip/fasticlip.py", line 5, in <module>
  File "build/bdist.linux-x86_64/egg/fasticlip/helper.py", line 13, in <module>
  File "/home/mecc/.local/lib/python2.7/site-packages/matplotlib/__init__.py", line 928, in __setitem__
    raise ValueError("Key %s: %s" % (key, str(ve)))
ValueError: Key savefig.dpi: "figurefigure" is not string "figure" or could not convert "figurefigure" to float

```

**Comment by andypohl** [comment]
I don't think the example is working for anyone at the moment.  They've mentioned they're fixing/updating the example, but it's been a couple weeks.

**Comment by bdo311** [comment]
@marencc thanks for reporting this. The error message seems to indicate that there is an issue with loading matplotlib. 

What version do you have installed? To find out you can run this in the terminal:

python -c "import matplotlib; print matplotlib.__version__"

@andypohl We should have new example data up over the next few days. Thanks for your patience!

**Comment by marencc** [comment]
@bdo311  

Hi! 

Thanks for your answer... 
The output of the command that you gave me is: 

python -c "import matplotlib; print matplotlib.version"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'version'
