### ISSUE TITLE
Can't run the example.

### ISSUE THREAD

**Issue by AmirArgoetti** [ChangLab/FAST-iCLIP#32]
Hello all,
I tried to run the example but it was failed (problem is attached).
Would you please advise me on how to proceed ?

Amir

``` 
amir@amir-VirtualBox:~/FAST-iCLIP$ fasticlip -i '/home/amir/FAST-iCLIP/rawdata/A_Human_Test_R1.fastq' '/home/amir/FAST-iCLIP/rawdata/A_Human_Test_R2.fastq'  --GRCh38 -n MMhur -o '/home/amir/FAST-iCLIP/results' 
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
[E::bgzf_flush] File write failed (wrong size)
samtools view: writing to "-" failed: Broken pipe
[E::bgzf_close] File write failedcat: write error: Broken pipe

samtools view: error closing "-": -1
Failed to open BAM file /home/amir/FAST-iCLIP/results/MMhur/A_Human_Test_R1_trimmed_mappedToDV_sorted.bam
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
[E::bgzf_flush] File write failed (wrong size)
samtools view: error closing "-": -1
Failed to open BAM file /home/amir/FAST-iCLIP/results/MMhur/A_Human_Test_R1_trimmed_mappedToZV_sorted.bam
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
[E::bgzf_flush] File write failed (wrong size)
samtools view: error closing "-": -1
Failed to open BAM file /home/amir/FAST-iCLIP/results/MMhur/A_Human_Test_R1_trimmed_mappedToHCV_JFH1_sorted.bam
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
[E::bgzf_flush] File write failed (wrong size)
samtools view: writing to "-" failed: Broken pipe
cat: write error: Broken pipe
[E::bgzf_close] File write failed
samtools view: error closing "-": -1
Failed to open BAM file /home/amir/FAST-iCLIP/results/MMhur/A_Human_Test_R2_trimmed_mappedToDV_sorted.bam
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
[E::bgzf_flush] File write failed (wrong size)
samtools view: error closing "-": -1
Failed to open BAM file /home/amir/FAST-iCLIP/results/MMhur/A_Human_Test_R2_trimmed_mappedToZV_sorted.bam
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
[E::bgzf_flush] File write failed (wrong size)
samtools view: error closing "-": -1
Failed to open BAM file /home/amir/FAST-iCLIP/results/MMhur/A_Human_Test_R2_trimmed_mappedToHCV_JFH1_sorted.bam
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
[E::bgzf_flush] File write failed (wrong size)
samtools view: writing to "-" failed: Broken pipe
cat: write error: Broken pipe
[E::bgzf_close] File write failed
samtools view: error closing "-": -1
Failed to open BAM file /home/amir/FAST-iCLIP/results/MMhur/A_Human_Test_R1_trimmed_mappedToRepeat_sorted.bam
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
[E::bgzf_flush] File write failed (wrong size)
samtools view: writing to "-" failed: Broken pipe
cat: write error: Broken pipe
[E::bgzf_close] File write failed
samtools view: error closing "-": -1
Failed to open BAM file /home/amir/FAST-iCLIP/results/MMhur/A_Human_Test_R2_trimmed_mappedToRepeat_sorted.bam
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
[E::bgzf_flush] File write failed (wrong size)
samtools view: writing to "-" failed: Broken pipe
cat: write error: Broken pipe
[E::bgzf_close] File write failed
samtools view: error closing "-": -1
Failed to open BAM file /home/amir/FAST-iCLIP/results/MMhur/A_Human_Test_R1_trimmed_mappedToendoVirus_sorted.bam
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
[E::bgzf_flush] File write failed (wrong size)
samtools view: writing to "-" failed: Broken pipe
cat: write error: Broken pipe
[E::bgzf_close] File write failed
samtools view: error closing "-": -1
Failed to open BAM file /home/amir/FAST-iCLIP/results/MMhur/A_Human_Test_R2_trimmed_mappedToendoVirus_sorted.bam
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
[E::bgzf_flush] File write failed (wrong size)
[main_samview] failed to write the SAM header
cat: write error: Broken pipe
[E::bgzf_close] File write failed
samtools view: error closing "-": -1
Failed to open BAM file /home/amir/FAST-iCLIP/results/MMhur/A_Human_Test_R1_trimmed_mappedToTrna_sorted.bam
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
[E::bgzf_flush] File write failed (wrong size)
samtools view: error closing "-": -1
Failed to open BAM file /home/amir/FAST-iCLIP/results/MMhur/A_Human_Test_R2_trimmed_mappedToTrna_sorted.bam
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
cat: /home/amir/FAST-iCLIP/results/MMhur/A_Human_Test_R1_trimmed_mappedToGenome.sam: No such file or directory
[E::bgzf_close] File write failed
samtools view: error closing "-": -1
Failed to open BAM file /home/amir/FAST-iCLIP/results/MMhur/A_Human_Test_R1_trimmed_mappedToGenome_sorted.bam
cat: [bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
/home/amir/FAST-iCLIP/results/MMhur/A_Human_Test_R2_trimmed_mappedToGenome.sam: No such file or directory
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
[E::bgzf_close] File write failed
samtools view: error closing "-": -1
Failed to open BAM file /home/amir/FAST-iCLIP/results/MMhur/A_Human_Test_R2_trimmed_mappedToGenome_sorted.bam
ERROR: Database file /home/amir/FAST-iCLIP/docs/GRCh38/GRCh38_repeatMasker.bed contains chromosome chr1, but the query file does not.
       Please re-reun with the -g option for a genome file.
       See documentation for details.
ERROR: Database file /home/amir/FAST-iCLIP/docs/GRCh38/GRCh38_repeatMasker.bed contains chromosome chr1, but the query file does not.
       Please re-reun with the -g option for a genome file.
       See documentation for details.
ERROR: Database file /home/amir/FAST-iCLIP/docs/GRCh38/GRCh38_repeatMasker.bed contains chromosome chr1, but the query file does not.
       Please re-reun with the -g option for a genome file.
       See documentation for details.
ERROR: Database file /home/amir/FAST-iCLIP/docs/GRCh38/GRCh38_repeatMasker.bed contains chromosome chr1, but the query file does not.
       Please re-reun with the -g option for a genome file.
       See documentation for details.
Error: Unable to open file /home/amir/FAST-iCLIP/docs/GRCh38/snoRNA_coordinates_15exp.bed. Exiting.
Error: Unable to open file /home/amir/FAST-iCLIP/docs/GRCh38/snoRNA_coordinates_15exp.bed. Exiting.
ERROR: Database file /home/amir/FAST-iCLIP/docs/GRCh38/miR_sort_clean.bed contains chromosome chr1, but the query file does not.
       Please re-reun with the -g option for a genome file.
       See documentation for details.
ERROR: Database file /home/amir/FAST-iCLIP/docs/GRCh38/genes_BED6.bed contains chromosome chr1, but the query file does not.
       Please re-reun with the -g option for a genome file.
       See documentation for details.
needLargeMem: trying to allocate 0 bytes (limit: 17179869184)
needLargeMem: trying to allocate 0 bytes (limit: 17179869184)
needLargeMem: trying to allocate 0 bytes (limit: 17179869184)
Traceback (most recent call last):
  File "/home/amir/.local/bin/fasticlip", line 11, in <module>
    load_entry_point('fasticlip==0.9.3', 'console_scripts', 'fasticlip')()
  File "build/bdist.linux-x86_64/egg/fasticlip/fasticlip.py", line 331, in main
  File "build/bdist.linux-x86_64/egg/fasticlip/helper.py", line 570, in get_gene_counts
  File "/home/amir/miniconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 705, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/amir/miniconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 445, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/amir/miniconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 814, in __init__
    self._make_engine(self.engine)
  File "/home/amir/miniconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 1045, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/amir/miniconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 1684, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 565, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
amir@amir-VirtualBox:~/FAST-iCLIP$

**Comment by MTVeno** [comment]
Hi, 
I have solved some of the problems running the example data, but it still does not run till completion.
Amir, I am pretty sure you are using a version of samtools that is too recent. Newer versions of samtools changed the output from samtools sort. Try using the one that comes with the FAST-iCLIP software in dependecies/

Also, I found that the GRCh38 bowtie2 index is not downloaded when one runs ./configure. I had to download it (from here: http://bowtie-bio.sourceforge.net/bowtie2/index.shtml) and rename to fit the hard-coded index name: docs/GRCh38/GRCh38_bowtie/GRCh38

Furthermore, the hard-coded snoRNA file is named incorrectly. I had to rename docs/GRCh38/snoRNA_coordinates.bed to docs/GRCh38/snoRNA_coordinates_15exp.bed

With these additions I was able to start the example, which ran for about 25 minutes, but failed. When I check the output files in the results folder it seems like the snoRNAs might be the problem. The first empty file generated is "clipGenes_snoRNA_reads.bed"

Here is how I ran the example data and the error messages:
```
~/software/FAST-iCLIP> fasticlip -i rawdata/A_Human_Test_R1.fastq rawdata/A_Human_Test_R2.fastq --GRCh38 -n Human_test -o results
/usr/local/lib/python2.7/dist-packages/matplotlib-2.0.0b3-py2.7-linux-x86_64.egg/matplotlib/font_manager.py:279: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
[samopen] SAM header is present: 1 sequences.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[samopen] SAM header is present: 1 sequences.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[samopen] SAM header is present: 1 sequences.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[samopen] SAM header is present: 1 sequences.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[samopen] SAM header is present: 1 sequences.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[samopen] SAM header is present: 1 sequences.
[samopen] SAM header is present: 1 sequences.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[samopen] SAM header is present: 1 sequences.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[samopen] SAM header is present: 1 sequences.
[samopen] SAM header is present: 1 sequences.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[samopen] SAM header is present: 625 sequences.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[samopen] SAM header is present: 625 sequences.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[samopen] SAM header is present: 195 sequences.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[samopen] SAM header is present: 195 sequences.
Traceback (most recent call last):
  File "/usr/local/bin/fasticlip", line 9, in <module>
    load_entry_point('fasticlip==0.9.3', 'console_scripts', 'fasticlip')()
  File "/usr/local/lib/python2.7/dist-packages/fasticlip-0.9.3-py2.7.egg/fasticlip/fasticlip.py", line 331, in main
    geneCounts_pc = get_gene_counts(proteinCodingReads_centered)
  File "/usr/local/lib/python2.7/dist-packages/fasticlip-0.9.3-py2.7.egg/fasticlip/helper.py", line 570, in get_gene_counts
    bf=pd.DataFrame(pd.read_table(bedFile,header=None))
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.18.1_345.g4a80521-py2.7-linux-x86_64.egg/pandas/io/parsers.py", line 647, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.18.1_345.g4a80521-py2.7-linux-x86_64.egg/pandas/io/parsers.py", line 390, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.18.1_345.g4a80521-py2.7-linux-x86_64.egg/pandas/io/parsers.py", line 731, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.18.1_345.g4a80521-py2.7-linux-x86_64.egg/pandas/io/parsers.py", line 910, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.18.1_345.g4a80521-py2.7-linux-x86_64.egg/pandas/io/parsers.py", line 1376, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "parser.pyx", line 538, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:5517)
pandas.io.common.EmptyDataError: No columns to parse from file

```
